# Generated by Django 5.0.3 on 2024-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbituser',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitbituser',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
