# Generated by Django 5.0.3 on 2024-04-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temps_debut', models.TimeField()),
                ('temps_fin', models.TimeField()),
                ('detail_level', models.CharField(choices=[('1sec', '1 Second'), ('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes')], default='1min', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('min_heart_rate', models.FloatField(blank=True, null=True)),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentations.experimentation')),
                ('pilote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotes.pilote')),
            ],
        ),
        migrations.CreateModel(
            name='HeartRateMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_mesure', models.TimeField()),
                ('fréquence_cardiaque', models.IntegerField()),
                ('participant_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_measurements', to='experimentations.participantexperiment')),
            ],
        ),
    ]
