# Generated by Django 5.0.3 on 2024-04-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pilote_photos/')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('fitbit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilotes', to='fitbit.fitbituser')),
            ],
        ),
    ]
